import { StyleSheet } from 'react-native';
import { COLORS } from './constants';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontWeight: '600',
    color: COLORS.text.primary,
  },
  refreshButton: {
    padding: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  loadingText: {
    color: COLORS.text.primary,
    marginTop: 16,
  },
  errorContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.error,
    padding: 12,
    margin: 16,
    borderRadius: 8,
  },
  errorText: {
    color: COLORS.text.light,
    marginLeft: 8,
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  ordersContainer: {
    padding: 16,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontWeight: "600",
    color: COLORS.text.primary,
  },
  orderCountBadge: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  orderCountText: {
    color: COLORS.text.light,
    fontWeight: "600",
  },
  orderList: {
    paddingBottom: 12,
  },
  orderCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 8,
    padding: 12,
    marginVertical: 4,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    elevation: 1,
  },
  selectedOrderCard: {
    borderWidth: 2,
    borderColor: COLORS.primary,
    backgroundColor: "#F0F8FF",
    shadowColor: COLORS.primary,
    shadowOpacity: 0.2,
  },
  orderCardContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 50,
  },
  orderLeftSection: {
    flex: 1,
  },
  orderCenterSection: {
    flex: 1,
    alignItems: "center",
  },
  customerNameText: {
    color: COLORS.text.secondary,
    marginTop: 2,
  },
  statusContainer: {
    marginTop: 2,
  },
  cancelledStatusText: {
    color: COLORS.error,
    fontWeight: "500",
  },
  processedStatusText: {
    color: COLORS.success,
    fontWeight: "500",
  },
  rejectedStatusText: {
    color: COLORS.error,
    fontWeight: "500",
  },
  approvalStatusText: {
    fontWeight: "600",
    textAlign: "center",
  },
  orderInfo: {
    flex: 1,
    marginRight: 16,
  },
  orderHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  orderIdText: {
    fontWeight: "600",
    color: COLORS.text.primary,
  },
  orderStatusContainer: {
    flexDirection: "row",
    gap: 8,
  },
  processedBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E6FFED",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  processedText: {
    color: COLORS.success,
    fontWeight: "600",
    marginLeft: 4,
  },
  cancelledBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEE2E2",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  cancelledText: {
    color: COLORS.error,
    fontWeight: "600",
    marginLeft: 4,
  },
  rejectedBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEE2E2",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  rejectedText: {
    color: COLORS.error,
    fontWeight: "600",
    marginLeft: 4,
  },
  orderDetails: {
    flexDirection: "column",
    gap: 8,
  },
  orderDetail: {
    flexDirection: "row",
    alignItems: "center",
  },
  orderDetailText: {
    color: COLORS.text.secondary,
    marginLeft: 6,
  },
  orderActionsContainer: {
    alignItems: "flex-end",
    justifyContent: "space-between",
    height: "100%",
    minHeight: 50,
  },
  orderAmountText: {
    fontWeight: "600", 
    color: COLORS.primary,
  },
  cancelOrderButton: {
    backgroundColor: COLORS.warning,
    padding: 6,
    borderRadius: 6,
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  disabledCancelButton: {
    backgroundColor: COLORS.text.tertiary,
    shadowOpacity: 0,
    elevation: 0,
  },
  orderSeparator: {
    height: 1,
    backgroundColor: COLORS.divider,
    marginVertical: 8,
  },
  editContainer: {
    backgroundColor: COLORS.surface,
    padding: 16,
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  orderStatusBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  orderStatusBannerText: {
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
  },
  orderDetailsCard: {
    backgroundColor: COLORS.background,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  orderDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  orderDetailItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  orderStatusContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
  },
  approvalStatusContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: COLORS.background,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  orderStatusText: {
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 6,
  },
  editHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  addProductButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  addProductButtonText: {
    color: COLORS.text.light,
    marginLeft: 6,
    fontSize: 14,
    fontWeight: "600",
  },
  disabledButton: {
    backgroundColor: COLORS.text.tertiary,
  },
  productCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  productContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  productImageContainer: {
    width: 60,
    height: 60,
    marginRight: 12,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: COLORS.divider,
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  noImageContainer: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  productDetails: {
    flex: 1,
  },
  productName: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.text.primary,
    marginBottom: 4,
  },
  productPrice: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.primary,
    marginBottom: 2,
  },
  productCategory: {
    fontSize: 12,
    color: COLORS.text.secondary,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  disabledEditButton: {
    opacity: 0.5,
  },
  editButtonText: {
    fontSize: 12,
    color: COLORS.primary,
    marginLeft: 4,
  },
  disabledEditButtonText: {
    color: COLORS.text.tertiary,
  },
  productActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deleteButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEE2E2',
    borderRadius: 8,
  },
  productSeparator: {
    height: 1,
    backgroundColor: COLORS.divider,
    marginVertical: 8,
  },
  summaryContainer: {
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 14,
    color: COLORS.text.secondary,
    fontWeight: "500",
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.text.primary,
  },
  summaryAmount: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.primary,
  },
  footer: {
    marginTop: 16,
  },
  updateButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  updateButtonText: {
    color: COLORS.text.light,
    fontSize: 16,
    fontWeight: "600",
  },
  emptyContainer: {
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.text.primary,
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 14,
    color: COLORS.text.secondary,
    marginTop: 8,
    textAlign: "center",
  },
  emptyProductsContainer: {
    justifyContent: "center",
    alignItems: "center",
    padding: 30,
    backgroundColor: COLORS.background,
    borderRadius: 12,
    marginVertical: 12,
  },
  emptyProductsText: {
    fontSize: 16,
    color: COLORS.text.secondary,
    marginVertical: 12,
  },
  addProductsButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 10,
  },
  addProductsButtonText: {
    color: COLORS.text.light,
    fontSize: 14,
    fontWeight: "600",
  },
  // Modal styles
  modalBackground: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  editModalContainer: {
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    width: '90%',
    maxWidth: 400,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  editModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  editModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.text.primary,
  },
  modalCloseButton: {
    padding: 4,
  },
  editModalContent: {
    padding: 16,
  },
  editItemName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.text.primary,
    marginBottom: 16,
  },
  editInputRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  editInputContainer: {
    flex: 1,
  },
  editInputLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.text.primary,
    marginBottom: 6,
  },
  editTextInput: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: COLORS.surface,
    color: COLORS.text.primary,
  },
  disabledInput: {
    backgroundColor: COLORS.divider,
    color: COLORS.text.tertiary,
  },
  priceRangeText: {
    fontSize: 12,
    color: COLORS.text.secondary,
    marginTop: 4,
  },
  disabledPriceText: {
    fontSize: 12,
    color: COLORS.text.tertiary,
    marginTop: 4,
    fontStyle: 'italic',
  },
  editModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  editCancelButton: {
    flex: 1,
    backgroundColor: COLORS.divider,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  editCancelText: {
    color: COLORS.text.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  editSaveButton: {
    flex: 1,
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  editSaveText: {
    color: COLORS.text.light,
    fontSize: 16,
    fontWeight: '600',
  },
  cancelledBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 8,
  },
  cancelledText: {
    color: COLORS.error,
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 4,
  },
  cancelledStateContainer: {
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  cancelledBadgeCentered: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  cancelledTextCentered: {
    color: COLORS.error,
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 6,
  },
  rejectedStateContainer: {
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  rejectedBadgeCentered: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  rejectedTextCentered: {
    color: COLORS.error,
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 6,
  },
  cancelledFilterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    justifyContent: 'space-between',
  },
  cancelledFilterLabel: {
    fontSize: 14,
    color: COLORS.text.primary,
    fontWeight: '500',
  },
  cancelledFilterPicker: {
    width: 100,
    height: 28,
    marginLeft: 8,
  },
  // Restricted order styles
  restrictedProductCard: {
    opacity: 0.6,
    backgroundColor: COLORS.divider,
  },
  restrictedProductImage: {
    opacity: 0.7,
  },
  restrictedNoImageContainer: {
    backgroundColor: COLORS.divider,
  },
  restrictedProductText: {
    color: COLORS.text.tertiary,
  },
  restrictionText: {
    fontSize: 12,
    fontStyle: 'italic',
    marginTop: 4,
    textAlign: 'center',
  },
});

export default styles;